/****************************************************************
   This file was created automatically by `FlexCat 2.16'
   from "/home/gavinr/svnwork/mycode/amigasource2/AROS-20180618-source/workbench/tools/gavin-commodities/catalogs/commodities.cd".

   Do NOT edit by hand!
****************************************************************/

#ifndef COMMODITIES_STRINGS_H
#define COMMODITIES_STRINGS_H


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif


#ifdef CATCOMP_ARRAY
#ifndef CATCOMPARRAY
#define CATCOMPARRAY CatCompArray
#endif
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif

/***************************************************************/

#ifdef CATCOMP_NUMBERS

#define MSG_CANT_OPEN_LIB 0
#define MSG_CANT_OPEN_INPUTDEVICE 1
#define MSG_CANT_OPEN_CLIPDEVICE 2
#define MSG_CANT_LOCK_SCR 3
#define MSG_CANT_GET_VI 4
#define MSG_CANT_CREATE_GADGET 5
#define MSG_CANT_CREATE_MENUS 6
#define MSG_CANT_LAYOUT_MENUS 7
#define MSG_CANT_CREATE_WIN 8
#define MSG_CANT_ALLOCATE_MEM 9
#define MSG_CANT_CREATE_MSGPORT 10
#define MSG_CANT_ALLOCATE_SIGNAL 11
#define MSG_CANT_CREATE_BROKER 12
#define MSG_CANT_CREATE_CUSTOM 13
#define MSG_OK 14
#define MSG_MEN_PROJECT 15
#define MSG_MEN_PROJECT_HIDE 16
#define MSG_MEN_PROJECT_ICONIFY 17
#define MSG_MEN_PROJECT_QUIT 18
#define MSG_EXCHANGE_CXNAME 19
#define MSG_EXCHANGE_CXTITLE 20
#define MSG_EXCHANGE_CXDESCR 21
#define MSG_EXCHANGE_WINTITLE 22
#define MSG_EXCHANGE_LISTVIEW 23
#define MSG_EXCHANGE_INFO 24
#define MSG_EXCHANGE_GAD_SHOW 25
#define MSG_EXCHANGE_GAD_HIDE 26
#define MSG_EXCHANGE_GAD_REMOVE 27
#define MSG_EXCHANGE_CYCLE_ACTIVE 28
#define MSG_EXCHANGE_CYCLE_INACTIVE 29
#define MSG_BLANKER_CXNAME 30
#define MSG_BLANKER_CXTITLE 31
#define MSG_BLANKER_CXDESCR 32
#define MSG_CLICK2FNT_CXNAME 33
#define MSG_CLICK2FNT_CXTITLE 34
#define MSG_CLICK2FNT_CXDESCR 35
#define MSG_OPAQUE_CXNAME 36
#define MSG_OPAQUE_CXTITLE 37
#define MSG_OPAQUE_CXDESCR 38
#define MSG_AUTOPOINT_CXNAME 39
#define MSG_AUTOPOINT_CXTITLE 40
#define MSG_AUTOPOINT_CXDESCR 41
#define MSG_STARTMENU_CXNAME 42
#define MSG_STARTMENU_CXTITLE 43
#define MSG_STARTMENU_CXDESCR 44
#define MSG_FKEY_CXNAME 45
#define MSG_FKEY_CXTITLE 46
#define MSG_FKEY_CXDESCR 47
#define MSG_FKEY_WINTITLE 48
#define MSG_FKEY_DEFINED_KEYS 49
#define MSG_FKEY_NEW_KEY 50
#define MSG_FKEY_DELETE_KEY 51
#define MSG_FKEY_SAVE_KEY 52
#define MSG_FKEY_COMMAND 53
#define MSG_FKEY_COMMAND_PARAMS 54
#define MSG_FKEY_CMD_CYCLE_WIN 55
#define MSG_FKEY_CMD_CYCLE_SCR 56
#define MSG_FKEY_CMD_ENLARGE_WIN 57
#define MSG_FKEY_CMD_SHRINK_WIN 58
#define MSG_FKEY_CMD_TOGGLE_WIN_SIZE 59
#define MSG_FKEY_CMD_RESCUE_WIN 60
#define MSG_FKEY_CMD_INSERT_TEXT 61
#define MSG_FKEY_CMD_RUN_PROG 62
#define MSG_FKEY_CMD_RUN_AREXX 63
#define MSG_FKEY_MEN_PROJECT_SAVE 64
#define MSG_NOCAPSLOCK_CXNAME 65
#define MSG_NOCAPSLOCK_CXTITLE 66
#define MSG_NOCAPSLOCK_CXDESCR 67
#define MSG_DEPTHMENU_CXNAME 68
#define MSG_DEPTHMENU_CXTITLE 69
#define MSG_DEPTHMENU_CXDESCR 70
#define MSG_ALTKEYQ_CXNAME 71
#define MSG_ALTKEYQ_CXTITLE 72
#define MSG_ALTKEYQ_CXDESCR 73
#define MSG_ASCIITABLE_CXNAME 74
#define MSG_ASCIITABLE_CXTITLE 75
#define MSG_ASCIITABLE_CXDESCR 76
#define MSG_ASCIITABLE_WINTITLE 77
#define MSG_ASCIITABLE_GAD_COPY 78
#define MSG_ASCIITABLE_GAD_CLEAR 79

#endif /* CATCOMP_NUMBERS */

/***************************************************************/

#ifdef CATCOMP_STRINGS

#define MSG_CANT_OPEN_LIB_STR "Can't open %s V%ld!\n"
#define MSG_CANT_OPEN_INPUTDEVICE_STR "Can't open 'input.device'"
#define MSG_CANT_OPEN_CLIPDEVICE_STR "Can't open 'clipboard.device'"
#define MSG_CANT_LOCK_SCR_STR "Can't lock public screen!\n"
#define MSG_CANT_GET_VI_STR "Can't get VisualInfo!\n"
#define MSG_CANT_CREATE_GADGET_STR "Can't create gadgets!\n"
#define MSG_CANT_CREATE_MENUS_STR "Can't create menus!\n"
#define MSG_CANT_LAYOUT_MENUS_STR "Can't layout menus!\n"
#define MSG_CANT_CREATE_WIN_STR "Can't create window!\n"
#define MSG_CANT_ALLOCATE_MEM_STR "Can't allocate application memory!\n"
#define MSG_CANT_CREATE_MSGPORT_STR "Can't create message port!\n"
#define MSG_CANT_ALLOCATE_SIGNAL_STR "Can't allocate signal!\n"
#define MSG_CANT_CREATE_BROKER_STR "Can't create CxBroker object!\n"
#define MSG_CANT_CREATE_CUSTOM_STR "Can't create CxCustom object!\n"
#define MSG_OK_STR "Ok"
#define MSG_MEN_PROJECT_STR "Project"
#define MSG_MEN_PROJECT_HIDE_STR "H\000Hide"
#define MSG_MEN_PROJECT_ICONIFY_STR "I\000Iconify"
#define MSG_MEN_PROJECT_QUIT_STR "Q\000Quit"
#define MSG_EXCHANGE_CXNAME_STR "Exchange"
#define MSG_EXCHANGE_CXTITLE_STR "Commodities Exchange"
#define MSG_EXCHANGE_CXDESCR_STR "Controls system commodities"
#define MSG_EXCHANGE_WINTITLE_STR "Exchange: Hot Key = <%s>"
#define MSG_EXCHANGE_LISTVIEW_STR "Available commodities"
#define MSG_EXCHANGE_INFO_STR "Information"
#define MSG_EXCHANGE_GAD_SHOW_STR "Show"
#define MSG_EXCHANGE_GAD_HIDE_STR "Hide"
#define MSG_EXCHANGE_GAD_REMOVE_STR "Remove"
#define MSG_EXCHANGE_CYCLE_ACTIVE_STR "Active"
#define MSG_EXCHANGE_CYCLE_INACTIVE_STR "Inactive"
#define MSG_BLANKER_CXNAME_STR "Blanker"
#define MSG_BLANKER_CXTITLE_STR "System Screen Blanker"
#define MSG_BLANKER_CXDESCR_STR "Blanks screen when system inactive"
#define MSG_CLICK2FNT_CXNAME_STR "ClickToFront"
#define MSG_CLICK2FNT_CXTITLE_STR "Click To Front Utility"
#define MSG_CLICK2FNT_CXDESCR_STR "Click windows to front"
#define MSG_OPAQUE_CXNAME_STR "Opaque"
#define MSG_OPAQUE_CXTITLE_STR "Solid Windows"
#define MSG_OPAQUE_CXDESCR_STR "Realtime moving of windows"
#define MSG_AUTOPOINT_CXNAME_STR "AutoPoint"
#define MSG_AUTOPOINT_CXTITLE_STR "Autopointer"
#define MSG_AUTOPOINT_CXDESCR_STR "Activates the window under the mouse"
#define MSG_STARTMENU_CXNAME_STR "StartMenu"
#define MSG_STARTMENU_CXTITLE_STR "System Program Starter"
#define MSG_STARTMENU_CXDESCR_STR "Program launch commodity"
#define MSG_FKEY_CXNAME_STR "FKey"
#define MSG_FKEY_CXTITLE_STR "Function To Keys:"
#define MSG_FKEY_CXDESCR_STR "Attach special functions to keys"
#define MSG_FKEY_WINTITLE_STR "FKey: Hot Key = <%s>"
#define MSG_FKEY_DEFINED_KEYS_STR "Defined Keys"
#define MSG_FKEY_NEW_KEY_STR "_New Key"
#define MSG_FKEY_DELETE_KEY_STR "_Delete Key"
#define MSG_FKEY_SAVE_KEY_STR "Save Defined Keys"
#define MSG_FKEY_COMMAND_STR "Command"
#define MSG_FKEY_COMMAND_PARAMS_STR "Command Parameters"
#define MSG_FKEY_CMD_CYCLE_WIN_STR "Cycle Windows"
#define MSG_FKEY_CMD_CYCLE_SCR_STR "Cycle Screens"
#define MSG_FKEY_CMD_ENLARGE_WIN_STR "Enlarge Window"
#define MSG_FKEY_CMD_SHRINK_WIN_STR "Shrink Window"
#define MSG_FKEY_CMD_TOGGLE_WIN_SIZE_STR "Toggle Window Size"
#define MSG_FKEY_CMD_RESCUE_WIN_STR "Rescue Window"
#define MSG_FKEY_CMD_INSERT_TEXT_STR "Insert Text"
#define MSG_FKEY_CMD_RUN_PROG_STR "Run Program"
#define MSG_FKEY_CMD_RUN_AREXX_STR "Run Arexx Script"
#define MSG_FKEY_MEN_PROJECT_SAVE_STR "S\000Save Defined Keys"
#define MSG_NOCAPSLOCK_CXNAME_STR "NoCapsLock"
#define MSG_NOCAPSLOCK_CXTITLE_STR "NoCapsLock:"
#define MSG_NOCAPSLOCK_CXDESCR_STR "Renders the CAPS LOCK key ineffective"
#define MSG_DEPTHMENU_CXNAME_STR "DepthMenu"
#define MSG_DEPTHMENU_CXTITLE_STR "DepthMenu:"
#define MSG_DEPTHMENU_CXDESCR_STR "Popup menu for depth gadgets"
#define MSG_ALTKEYQ_CXNAME_STR "AltKeyQ"
#define MSG_ALTKEYQ_CXTITLE_STR "Character input by number"
#define MSG_ALTKEYQ_CXDESCR_STR "MS-DOS Style Alt key usage"
#define MSG_ASCIITABLE_CXNAME_STR "ASCIITable"
#define MSG_ASCIITABLE_CXTITLE_STR "ASCIITable:"
#define MSG_ASCIITABLE_CXDESCR_STR "Select keys from a GUI"
#define MSG_ASCIITABLE_WINTITLE_STR "ASCIITable: Hot Key = <%s>"
#define MSG_ASCIITABLE_GAD_COPY_STR "Copy"
#define MSG_ASCIITABLE_GAD_CLEAR_STR "Clear"

#endif /* CATCOMP_STRINGS */

/***************************************************************/

#ifdef CATCOMP_ARRAY

#ifndef HAVE_CATCOMP_ARRAYTYPE
#define HAVE_CATCOMP_ARRAYTYPE
struct CatCompArrayType
{
  IPTR   cca_ID;
  STRPTR cca_Str;
};
#endif

static const struct CatCompArrayType CATCOMPARRAY[] =
{
  {MSG_CANT_OPEN_LIB,(STRPTR)MSG_CANT_OPEN_LIB_STR},
  {MSG_CANT_OPEN_INPUTDEVICE,(STRPTR)MSG_CANT_OPEN_INPUTDEVICE_STR},
  {MSG_CANT_OPEN_CLIPDEVICE,(STRPTR)MSG_CANT_OPEN_CLIPDEVICE_STR},
  {MSG_CANT_LOCK_SCR,(STRPTR)MSG_CANT_LOCK_SCR_STR},
  {MSG_CANT_GET_VI,(STRPTR)MSG_CANT_GET_VI_STR},
  {MSG_CANT_CREATE_GADGET,(STRPTR)MSG_CANT_CREATE_GADGET_STR},
  {MSG_CANT_CREATE_MENUS,(STRPTR)MSG_CANT_CREATE_MENUS_STR},
  {MSG_CANT_LAYOUT_MENUS,(STRPTR)MSG_CANT_LAYOUT_MENUS_STR},
  {MSG_CANT_CREATE_WIN,(STRPTR)MSG_CANT_CREATE_WIN_STR},
  {MSG_CANT_ALLOCATE_MEM,(STRPTR)MSG_CANT_ALLOCATE_MEM_STR},
  {MSG_CANT_CREATE_MSGPORT,(STRPTR)MSG_CANT_CREATE_MSGPORT_STR},
  {MSG_CANT_ALLOCATE_SIGNAL,(STRPTR)MSG_CANT_ALLOCATE_SIGNAL_STR},
  {MSG_CANT_CREATE_BROKER,(STRPTR)MSG_CANT_CREATE_BROKER_STR},
  {MSG_CANT_CREATE_CUSTOM,(STRPTR)MSG_CANT_CREATE_CUSTOM_STR},
  {MSG_OK,(STRPTR)MSG_OK_STR},
  {MSG_MEN_PROJECT,(STRPTR)MSG_MEN_PROJECT_STR},
  {MSG_MEN_PROJECT_HIDE,(STRPTR)MSG_MEN_PROJECT_HIDE_STR},
  {MSG_MEN_PROJECT_ICONIFY,(STRPTR)MSG_MEN_PROJECT_ICONIFY_STR},
  {MSG_MEN_PROJECT_QUIT,(STRPTR)MSG_MEN_PROJECT_QUIT_STR},
  {MSG_EXCHANGE_CXNAME,(STRPTR)MSG_EXCHANGE_CXNAME_STR},
  {MSG_EXCHANGE_CXTITLE,(STRPTR)MSG_EXCHANGE_CXTITLE_STR},
  {MSG_EXCHANGE_CXDESCR,(STRPTR)MSG_EXCHANGE_CXDESCR_STR},
  {MSG_EXCHANGE_WINTITLE,(STRPTR)MSG_EXCHANGE_WINTITLE_STR},
  {MSG_EXCHANGE_LISTVIEW,(STRPTR)MSG_EXCHANGE_LISTVIEW_STR},
  {MSG_EXCHANGE_INFO,(STRPTR)MSG_EXCHANGE_INFO_STR},
  {MSG_EXCHANGE_GAD_SHOW,(STRPTR)MSG_EXCHANGE_GAD_SHOW_STR},
  {MSG_EXCHANGE_GAD_HIDE,(STRPTR)MSG_EXCHANGE_GAD_HIDE_STR},
  {MSG_EXCHANGE_GAD_REMOVE,(STRPTR)MSG_EXCHANGE_GAD_REMOVE_STR},
  {MSG_EXCHANGE_CYCLE_ACTIVE,(STRPTR)MSG_EXCHANGE_CYCLE_ACTIVE_STR},
  {MSG_EXCHANGE_CYCLE_INACTIVE,(STRPTR)MSG_EXCHANGE_CYCLE_INACTIVE_STR},
  {MSG_BLANKER_CXNAME,(STRPTR)MSG_BLANKER_CXNAME_STR},
  {MSG_BLANKER_CXTITLE,(STRPTR)MSG_BLANKER_CXTITLE_STR},
  {MSG_BLANKER_CXDESCR,(STRPTR)MSG_BLANKER_CXDESCR_STR},
  {MSG_CLICK2FNT_CXNAME,(STRPTR)MSG_CLICK2FNT_CXNAME_STR},
  {MSG_CLICK2FNT_CXTITLE,(STRPTR)MSG_CLICK2FNT_CXTITLE_STR},
  {MSG_CLICK2FNT_CXDESCR,(STRPTR)MSG_CLICK2FNT_CXDESCR_STR},
  {MSG_OPAQUE_CXNAME,(STRPTR)MSG_OPAQUE_CXNAME_STR},
  {MSG_OPAQUE_CXTITLE,(STRPTR)MSG_OPAQUE_CXTITLE_STR},
  {MSG_OPAQUE_CXDESCR,(STRPTR)MSG_OPAQUE_CXDESCR_STR},
  {MSG_AUTOPOINT_CXNAME,(STRPTR)MSG_AUTOPOINT_CXNAME_STR},
  {MSG_AUTOPOINT_CXTITLE,(STRPTR)MSG_AUTOPOINT_CXTITLE_STR},
  {MSG_AUTOPOINT_CXDESCR,(STRPTR)MSG_AUTOPOINT_CXDESCR_STR},
  {MSG_STARTMENU_CXNAME,(STRPTR)MSG_STARTMENU_CXNAME_STR},
  {MSG_STARTMENU_CXTITLE,(STRPTR)MSG_STARTMENU_CXTITLE_STR},
  {MSG_STARTMENU_CXDESCR,(STRPTR)MSG_STARTMENU_CXDESCR_STR},
  {MSG_FKEY_CXNAME,(STRPTR)MSG_FKEY_CXNAME_STR},
  {MSG_FKEY_CXTITLE,(STRPTR)MSG_FKEY_CXTITLE_STR},
  {MSG_FKEY_CXDESCR,(STRPTR)MSG_FKEY_CXDESCR_STR},
  {MSG_FKEY_WINTITLE,(STRPTR)MSG_FKEY_WINTITLE_STR},
  {MSG_FKEY_DEFINED_KEYS,(STRPTR)MSG_FKEY_DEFINED_KEYS_STR},
  {MSG_FKEY_NEW_KEY,(STRPTR)MSG_FKEY_NEW_KEY_STR},
  {MSG_FKEY_DELETE_KEY,(STRPTR)MSG_FKEY_DELETE_KEY_STR},
  {MSG_FKEY_SAVE_KEY,(STRPTR)MSG_FKEY_SAVE_KEY_STR},
  {MSG_FKEY_COMMAND,(STRPTR)MSG_FKEY_COMMAND_STR},
  {MSG_FKEY_COMMAND_PARAMS,(STRPTR)MSG_FKEY_COMMAND_PARAMS_STR},
  {MSG_FKEY_CMD_CYCLE_WIN,(STRPTR)MSG_FKEY_CMD_CYCLE_WIN_STR},
  {MSG_FKEY_CMD_CYCLE_SCR,(STRPTR)MSG_FKEY_CMD_CYCLE_SCR_STR},
  {MSG_FKEY_CMD_ENLARGE_WIN,(STRPTR)MSG_FKEY_CMD_ENLARGE_WIN_STR},
  {MSG_FKEY_CMD_SHRINK_WIN,(STRPTR)MSG_FKEY_CMD_SHRINK_WIN_STR},
  {MSG_FKEY_CMD_TOGGLE_WIN_SIZE,(STRPTR)MSG_FKEY_CMD_TOGGLE_WIN_SIZE_STR},
  {MSG_FKEY_CMD_RESCUE_WIN,(STRPTR)MSG_FKEY_CMD_RESCUE_WIN_STR},
  {MSG_FKEY_CMD_INSERT_TEXT,(STRPTR)MSG_FKEY_CMD_INSERT_TEXT_STR},
  {MSG_FKEY_CMD_RUN_PROG,(STRPTR)MSG_FKEY_CMD_RUN_PROG_STR},
  {MSG_FKEY_CMD_RUN_AREXX,(STRPTR)MSG_FKEY_CMD_RUN_AREXX_STR},
  {MSG_FKEY_MEN_PROJECT_SAVE,(STRPTR)MSG_FKEY_MEN_PROJECT_SAVE_STR},
  {MSG_NOCAPSLOCK_CXNAME,(STRPTR)MSG_NOCAPSLOCK_CXNAME_STR},
  {MSG_NOCAPSLOCK_CXTITLE,(STRPTR)MSG_NOCAPSLOCK_CXTITLE_STR},
  {MSG_NOCAPSLOCK_CXDESCR,(STRPTR)MSG_NOCAPSLOCK_CXDESCR_STR},
  {MSG_DEPTHMENU_CXNAME,(STRPTR)MSG_DEPTHMENU_CXNAME_STR},
  {MSG_DEPTHMENU_CXTITLE,(STRPTR)MSG_DEPTHMENU_CXTITLE_STR},
  {MSG_DEPTHMENU_CXDESCR,(STRPTR)MSG_DEPTHMENU_CXDESCR_STR},
  {MSG_ALTKEYQ_CXNAME,(STRPTR)MSG_ALTKEYQ_CXNAME_STR},
  {MSG_ALTKEYQ_CXTITLE,(STRPTR)MSG_ALTKEYQ_CXTITLE_STR},
  {MSG_ALTKEYQ_CXDESCR,(STRPTR)MSG_ALTKEYQ_CXDESCR_STR},
  {MSG_ASCIITABLE_CXNAME,(STRPTR)MSG_ASCIITABLE_CXNAME_STR},
  {MSG_ASCIITABLE_CXTITLE,(STRPTR)MSG_ASCIITABLE_CXTITLE_STR},
  {MSG_ASCIITABLE_CXDESCR,(STRPTR)MSG_ASCIITABLE_CXDESCR_STR},
  {MSG_ASCIITABLE_WINTITLE,(STRPTR)MSG_ASCIITABLE_WINTITLE_STR},
  {MSG_ASCIITABLE_GAD_COPY,(STRPTR)MSG_ASCIITABLE_GAD_COPY_STR},
  {MSG_ASCIITABLE_GAD_CLEAR,(STRPTR)MSG_ASCIITABLE_GAD_CLEAR_STR},
  {0,NULL}
};

#endif /* CATCOMP_ARRAY */

/***************************************************************/

#ifdef CATCOMP_BLOCK

#error CATCOMP_BLOCK not supported by this SD

#endif /* CATCOMP_BLOCK */

/***************************************************************/

#ifdef CATCOMP_CODE

#error CATCOMP_CODE not supported by this SD

#endif /* CATCOMP_CODE */

/***************************************************************/


#endif /* COMMODITIES_STRINGS_H */
